return {
	diagnostics = {
		error = " ",
		hint = " ",
		information = " ",
		other = " ",
		warning = " ",
	},
	git = {
		Added = " ",
		Modified = " ",
		Removed = " ",
	},
	dap = {
		breakpoint = " ",
		breakpoint_condition = " ",
		log_point = " ",
		stopped = " ",
		breakpoint_rejected = " ",
		pause = " ",
		play = " ",
		step_into = " ",
		step_over = " ",
		step_out = " ",
		step_back = " ",
		run_last = " ",
		terminate = " ",
	},
	lazy = {
		cmd = " ",
		config = "",
		event = "",
		ft = " ",
		init = " ",
		import = " ",
		keys = " ",
		lazy = "󰒲 ",
		loaded = "󱄲",
		not_loaded = "󱄯",
		plugin = " ",
		runtime = " ",
		source = " ",
		start = "",
		task = "✔ ",
		list = {
			"󱄰",
			"➜",
			"★",
			"‒",
		},
	},
	mason = {
		package_installed = "󱄲",
		package_pending = "󱄰",
		package_uninstalled = "󱄯",
	},
	borders = {
		dashed = { "┄", "┊", "┄", "┊", "╭", "╮", "╯", "╰", },
		double = { "═", "║", "═", "║", "╔", "╗", "╝", "╚", },
		single = { "─", "│", "─", "│", "╭", "╮", "╯", "╰", },
		blocks = { "▀", "▐", "▄", "▌", "▛", "▜", "▟", "▙", },
		blocky = { "▀", "▐", "▄", "▌", "▄", "▄", "▓", "▀", },
	},
	telescope = {
		prompt = { "┄", "┊", "┄", "┊", "╭", "╮", "╯", "╰", },
		results = { "┄", " ", "┄", "┊", "╭", "┄", "┄", "╰", },
		preview = { "┄", "┊", "┄", "┊", "┄", "╮", "╯", "╰", },
	},
}
