#!/bin/bash
filename="/tmp/herbstluftwm-gap"
while read -r line
do
	gap=$line
	if [ "$gap" -ge 0 ]; then
		gap=$((gap-10))
    	herbstclient set window_gap $gap
    fi
    echo $gap > $filename
done < "$filename"
